import pandas as pd

data = {
    "Query": [
        "What does the policy cover for theft?",
        "What are the exclusions for accidental damage?",
        "How do I file a claim for a car accident?",
        "What are the conditions for policy renewal?",
        "Who is allowed to drive my car?",
        "Am I covered if I leave my car unlocked?",
        "What is DriveSure?",
        "What’s the difference between commuting and business use?",
        "What should I do if my car is damaged?",
        "How is the market value of my car determined?",
        "Can I drive other cars with my insurance?",
        "What is covered under personal belongings?",
        "How does the No Claims Discount work?",
        "What is the excess I need to pay?",
        "Is there cover for driving abroad?",
        "What happens if I need to cancel my policy?",
        "What are the policy exclusions for theft?",
        "How do I get a courtesy car?",
        "What is the policy coverage for windscreen damage?",
        "What is covered under legal assistance?",
        "How do I update my policy details?",
        "What is covered under accidental damage?",
        "What is the claims process for vandalism?",
        "How can I pay for my insurance?",
        "What is the coverage for medical expenses?",
        "Are there any benefits for safe drivers?",
        "What is the definition of a total loss?",
        "How do I report a claim?",
        "Are modifications to my car covered?",
        "What is the coverage for personal injury?",
        "What does the policy say about third-party liability?",
        "What is the process for renewing my policy?",
        "Can I add additional drivers to my policy?",
        "How do I make changes to my existing policy?",
        "What documents do I need to provide when making a claim?",
        "Does the policy cover damage caused by natural disasters?",
        "What is the process for appealing a claim decision?",
        "Are there any discounts available for installing security devices?",
        "How long does the claims process typically take?",
        "What is covered under comprehensive insurance?",
        "What should I do if I need to make a complaint?",
        "Can I get insurance if I have previous claims?",
        "What does the policy cover for fire damage?",
        "How does the policy handle uninsured drivers?",
        "What are the payment options for my premium?",
        "What is the policy's stance on modifications and customizations?",
        "Does the policy cover hire cars while my car is being repaired?",
        "What are the policy's terms for accident liability?",
        "Does the policy provide cover for driver injury?",
        "What is the process for updating policy details?",
        "How are high-value items in the car insured?",
        "What kind of roadside assistance is included?",
        "Are there any limits on the number of claims?",
        "How does the policy address temporary vehicle use?",
        "What is the impact of claims on my premium?",
        "Does the policy cover international travel?",
        "How does the policy handle unlicensed drivers?",
        "What is the procedure for policy cancellation?",
        "How are disputes resolved under the policy?",
        "What is covered under the policy's collision damage?",
        "Are natural calamities like earthquakes covered?",
        "How can I apply for a No Claims Discount?",
        "What is the procedure for adding additional vehicles?",
        "Does the policy cover legal costs for traffic violations?",
        "What are the conditions for vehicle modifications?",
        "How does the policy treat wear and tear?"
    ],
    "Response": [
        "The policy provides coverage for theft of the insured vehicle, including the cost of repair or replacement. The incident must be reported to the police immediately and the insurance company should be provided with all necessary documentation, including a crime reference number. The policy also covers damage resulting from attempted theft. Key exclusions include theft when the car is left unlocked or with keys inside.",
        "Exclusions for accidental damage include incidents occurring when the driver is under the influence of alcohol or drugs, using the vehicle for purposes not specified in the policy, or if the damage is due to regular wear and tear. Accidental damage also does not cover the use of non-approved spare parts for repairs.",
        "To file a claim for a car accident, notify the insurer immediately with details of the accident, including time, date, and location. Provide a completed claim form along with supporting documents such as a police report, photographs of the damage, and witness statements if available. The insurer may also require a medical report if there were any injuries involved.",
        "Policy renewal is subject to an annual review of your driving history, claims record, and any changes in your personal or vehicle details. The insurer may adjust the premium based on these factors. It is essential to update any changes in your information to ensure continuous coverage without gaps.",
        "Typically, the policy allows anyone named on the insurance certificate to drive the car. This may include family members or designated individuals. However, each driver must hold a valid driving license and comply with the terms of the policy. Unauthorized drivers or those not named in the policy are not covered.",
        "The policy does not cover theft if the vehicle is left unlocked or if keys are left inside. Additionally, coverage is void if the vehicle is left unattended with the engine running or if windows are left open. It is crucial to secure your vehicle and remove keys to prevent theft and ensure coverage.",
        "DriveSure is a telematics-based insurance product that tracks how and where you drive using a small device installed in your car. It monitors driving behavior such as speed, braking, and mileage to adjust your insurance premium based on safe driving practices. DriveSure aims to reward safe drivers with lower premiums and provide insights into improving driving habits.",
        "Commuting refers to driving to and from a fixed place of work, while business use includes driving as part of your job, which may involve multiple destinations and clients. Business use generally covers more extensive driving activities and may impact your insurance premium differently than standard commuting.",
        "If your car is damaged, contact your insurer as soon as possible to report the incident. You will need to provide details such as your policy number, car registration, and a description of the damage. The insurer will guide you through the process of filing a claim, which may include providing photographs and arranging for repairs at an authorized service center.",
        "The market value of your car is determined by its current condition, mileage, age, and the value of similar cars in the market. The insurer may also consider factors such as the car’s previous accident history and maintenance records. The market value is the maximum amount the insurer will pay in the event of a total loss claim.",
        "Your policy may include coverage to drive other cars if explicitly stated. This often applies to driving a vehicle not owned by you or registered in your name, under certain conditions. Always check your policy document to confirm whether this cover is available and any specific limitations or requirements.",
        "Personal belongings coverage protects items stolen from your car, up to a specified limit. The policy typically covers items that are kept in a locked boot or glove compartment and excludes valuable items like cash or jewelry. Claims for personal belongings must be supported by proof of purchase and a police report.",
        "The No Claims Discount (NCD) reduces your premium for each year you do not make a claim. The discount accumulates over time, rewarding safe driving and no claims. If you make a claim, your NCD may be reduced or lost, depending on the terms of your policy and whether the claim is deemed your fault or not.",
        "The excess is the amount you must pay out of pocket towards a claim. The amount varies depending on the type of claim and the policy terms. For example, a higher excess might apply to theft or collision claims, while a lower excess might apply to windshield repairs. The excess amount can affect your premium; choosing a higher excess can reduce your premium costs.",
        "The policy may include coverage for driving in certain foreign countries. You may need to check your policy document for specific details about which countries are covered and under what conditions. Additional documentation, such as a Green Card or an International Driving Permit, may be required for international travel.",
        "To cancel your policy, contact your insurer directly. You may need to provide a written request or fill out a cancellation form. Depending on how long your policy has been in effect, you may be entitled to a partial refund. Cancellation terms, including fees or penalties, are detailed in the policy document.",
        "Exclusions for theft include situations where the car is left unlocked, with keys inside, or when the vehicle is left running unattended. Theft is also not covered if the policyholder fails to take reasonable precautions to protect the car, such as parking in a secure location or installing security devices.",
        "If eligible for a courtesy car, it will be provided while your car is being repaired after an insured event. The availability of a courtesy car depends on the policy terms and the nature of the damage. You may need to arrange for the courtesy car through a designated repair network or contact your insurer for further instructions.",
        "The policy typically covers the cost of repairing or replacing a damaged windscreen, subject to an excess. Some policies may also offer a no-excess option for windscreen repairs, allowing for a cost-free repair or replacement. Check your policy for specific details and any preferred repair service providers.",
        "Legal assistance covers the costs of legal services in case you need to defend or pursue a claim related to your car insurance policy. This may include legal fees, court costs, and expenses for legal representation. Coverage limits and exclusions are detailed in the policy document, so review it carefully to understand the scope of the legal assistance provided.",
        "To update your policy details, contact your insurer with the changes you need to make, such as a new address, changes in vehicle ownership, or adding a new driver. These updates may affect your premium and the terms of your coverage. Promptly report changes to avoid gaps in your insurance coverage.",
        "Accidental damage coverage includes repairs or replacement of your car following an accident, regardless of fault. This covers damages from collisions, impacts with objects, and single-vehicle accidents. The policy specifies limits and conditions for such claims, including any applicable excess you must pay.",
        "To claim for vandalism, first report the incident to the police and obtain a crime reference number. Contact your insurer to initiate the claim and provide details such as the incident description, damage photos, and the police report. The insurer will guide you through the process, which may include arranging repairs and assessing the damage.",
        "Insurance premiums can be paid in full annually or through monthly instalments. Payment options typically include direct debit, credit or debit cards, and online banking. Some insurers may offer discounts for full annual payments, so consider your payment options carefully when purchasing or renewing your policy.",
        "Medical expenses coverage includes the costs of medical treatment for injuries sustained in a car accident. This can cover emergency care, hospital stays, and rehabilitation expenses, up to the limits specified in your policy. Coverage may extend to both the policyholder and passengers injured in the accident.",
        "Safe drivers may benefit from lower premiums, No Claims Discounts, and other rewards. Some policies offer telematics or usage-based insurance, which monitors driving habits and provides discounts for safe driving behavior. Additional benefits may include accident forgiveness or access to safe driving courses.",
        "A total loss occurs when the cost of repairs exceeds the car’s market value or when the car is damaged beyond repair. In such cases, the insurer will compensate the policyholder with the car’s current market value. The determination of a total loss includes assessing the extent of damage and the repair costs compared to the car’s value.",
        "To report a claim, contact your insurer immediately with your policy number, a description of the incident, and any supporting documentation, such as photos or police reports. The insurer will provide instructions on completing the claim form and submitting additional evidence as needed.",
        "Modifications to your car are covered if they are declared and approved by the insurer. These may include performance enhancements, cosmetic changes, or added accessories. Non-approved modifications or those not declared may void coverage or result in denied claims.",
        "Personal injury coverage compensates for injuries sustained in an accident involving your car. This includes medical expenses, lost wages, and rehabilitation costs. Coverage limits are specified in the policy, and claims may require medical documentation and proof of the accident.",
        "Third-party liability coverage protects against claims from others for injury or damage caused by an accident involving your car. This includes legal liability for injuries to other drivers, passengers, or pedestrians and damage to their property. Coverage limits and exclusions are detailed in the policy document.",
        "To renew your policy, review your current coverage and update any information if necessary. Pay the renewal premium by the due date to avoid a lapse in coverage. The insurer may also provide a renewal notice with updated terms and premium details.",
        "Additional drivers can be added to your policy by providing their details, such as name, driving license number, and driving history. The addition of new drivers may affect your premium and coverage terms. Contact your insurer to update your policy and confirm the changes.",
        "To make changes to your existing policy, contact your insurer with the necessary details. Changes can include updating personal information, adding or removing drivers, or changing the vehicle covered. These changes may affect your premium and policy terms, so review them carefully.",
        "When making a claim, provide your policy number, completed claim form, proof of loss or damage, and any supporting documentation, such as photos, repair estimates, or police reports. Prompt submission of all required documents helps expedite the claims process.",
        "Damage caused by natural disasters, such as floods, storms, or earthquakes, may be covered under comprehensive insurance. Check your policy for specific details on coverage limits, exclusions, and any necessary documentation to support your claim.",
        "To appeal a claim decision, contact your insurer with additional information or documentation supporting your case. The insurer may review the claim and provide a decision based on the new evidence. If the appeal is unsuccessful, further steps may include contacting an ombudsman or seeking legal advice.",
        "Installing security devices such as alarms, immobilizers, or tracking systems may qualify you for discounts on your insurance premium. Check with your insurer to confirm eligibility and specific discounts available for security enhancements.",
        "The duration of the claims process varies depending on the complexity of the claim and the availability of necessary documentation. Simple claims may be resolved within a few days, while more complex claims can take several weeks. Insurers strive to process claims efficiently to minimize disruption to policyholders.",
        "Comprehensive insurance covers a wide range of incidents, including theft, fire, vandalism, and accidental damage to your car. It also includes third-party liability for damage or injury caused to others. Comprehensive coverage provides the highest level of protection for your vehicle.",
        "To make a complaint, contact your insurer’s customer service department with details of your issue. Provide relevant documentation and a clear explanation of your concerns. The insurer will investigate the complaint and aim to resolve it promptly. If you are not satisfied with the response, you may escalate the complaint to a regulatory authority.",
        "You can get insurance even if you have previous claims, although this may result in higher premiums or reduced coverage options. It’s important to disclose all previous claims accurately to avoid issues with policy validity or claim denials.",
        "The policy covers fire damage under comprehensive cover, including damage from accidental fires, arson, or mechanical failures. The coverage includes the cost of repairs or replacement up to the car’s market value. Check the policy for specific details on coverage limits and exclusions.",
        "The policy may cover damage caused by uninsured drivers under certain conditions. This can include compensation for injuries and damage to your car. The extent of coverage varies, so review the policy for specific details and any required documentation for claims involving uninsured drivers.",
        "Premiums can typically be paid annually in full or through monthly instalments. Payment methods include direct debit, credit or debit cards, and online banking. Review your policy documents for payment options and potential discounts for full annual payments.",
        "The policy allows certain modifications if declared and approved by the insurer. Common acceptable modifications include cosmetic changes and performance enhancements. Undeclared or non-approved modifications may void coverage or result in claim denials. Always consult with your insurer before making significant changes to your vehicle.",
        "If your car is being repaired following an insured incident, you may be eligible for a hire car for the duration of the repairs. The availability and terms of a hire car depend on the specifics of your policy and the nature of the damage.",
        "The policy details the responsibilities and liabilities in case of an accident, including coverage for third-party injuries and property damage. Policyholders must follow the procedure for reporting accidents and submitting claims to ensure coverage. Review the policy document for comprehensive details on accident liability.",
        "Driver injury cover provides compensation for injuries sustained by the driver in an accident involving the insured vehicle. This includes medical expenses, rehabilitation costs, and, in some cases, lost wages. Coverage limits and conditions are specified in the policy.",
        "To update policy details, contact your insurer with the necessary information, such as changes in personal details, address, or vehicle information. Updating your policy ensures accurate coverage and prevents gaps in insurance. Changes may affect your premium and policy terms.",
        "High-value items in the car, such as electronics or personal belongings, are insured up to a specified limit under personal belongings cover. Items must be secured in a locked compartment and require proof of purchase for claims. Review the policy for specific coverage limits and conditions.",
        "Roadside assistance coverage includes services such as towing, battery jump-starts, flat tire changes, and emergency fuel delivery. Coverage varies by policy, so check the specifics for limits and service providers. Some policies may also offer additional benefits like trip interruption coverage.",
        "There may be limits on the number of claims you can file within a policy period without affecting your premium or coverage. Excessive claims can lead to increased premiums or policy non-renewal. Review your policy for specific limits and guidelines on claim frequency.",
        "Temporary vehicle use, such as borrowing a car or renting a vehicle, may be covered if specified in your policy. Check the policy for details on temporary cover and any restrictions or requirements. Temporary vehicle use typically requires prior notification to the insurer.",
        "Making a claim can impact your premium, especially if you are deemed at fault. Claims may reduce your No Claims Discount and result in higher premiums at renewal. The impact depends on the claim type and your overall claims history. Review your policy for details on the impact of claims on premiums.",
        "The policy may provide coverage for driving in foreign countries under certain conditions. Check your policy for details on countries covered, duration of coverage, and any additional documentation required, such as a Green Card or International Driving Permit. Coverage terms for international travel vary by policy.",
        "The policy does not cover incidents involving unlicensed drivers. Drivers must hold a valid license and comply with any restrictions or conditions stated in the policy. Allowing an unlicensed driver to operate your vehicle can result in claim denial and policy cancellation.",
        "High-value vehicles, such as luxury cars, may require additional coverage or higher premiums due to their increased risk of theft or damage. Ensure that your policy provides adequate coverage for high-value vehicles, including comprehensive cover and higher coverage limits. Consult with your insurer for specific policy options for high-value vehicles.",
        "The policy includes coverage for rental cars while your vehicle is being repaired after an insured incident. This is subject to the policy terms and availability of rental vehicles. Coverage may include daily rental fees and additional insurance for the rental car. Review the policy for specific details and conditions for rental car coverage.",
        "Mechanical breakdowns are typically not covered under standard car insurance policies. However, optional coverage or a separate breakdown policy may be available. Check your policy for specific details on coverage for mechanical failures and additional options for breakdown protection.",
        "The policy does not provide coverage for natural calamities such as earthquakes. This exclusion means any damage or loss resulting from an earthquake would not be covered under this insurance policy.",
        "To apply for a No Claims Discount, you need to provide evidence of your claim-free record from your previous insurer. This can include a No Claims Discount certificate or a renewal notice showing the discount you have earned. If switching insurers, you may need to submit this documentation to your new insurer to maintain your discount.",
        "The procedure for adding additional vehicles to your policy involves contacting your insurer to update your policy details. You will need to provide information about the new vehicle, such as the make, model, and registration number. An additional premium may be required depending on the specifics of the new vehicle.",
        "The policy does not cover legal costs for traffic violations. This includes fines or penalties incurred as a result of violating traffic laws. Any legal expenses associated with defending against such violations are also excluded from coverage.",
        "Conditions for vehicle modifications include notifying your insurer about any changes made to your vehicle. Modifications must be approved and comply with manufacturer’s specifications. Failure to declare modifications can void coverage or affect claims.",
        "The policy treats wear and tear as an exclusion. This means normal deterioration or depreciation of the vehicle due to aging or usage is not covered. Any repairs or replacements needed as a result of wear and tear would be the responsibility of the vehicle owner."

    ]
}

query_size = len(data["Query"])
response_size = len(data["Response"])

print("Size of Query list:", query_size)
print("Size of Response list:", response_size)


# Convert to DataFrame
df = pd.DataFrame(data)

# Save to CSV
df.to_csv("query_respons.csv", index=False)

print("Dataset saved successfully.")
